name: blog
channels:
- anaconda-fusion
- https://conda.anaconda.org/ducva
- https://conda.anaconda.org/menpo
- defaults
dependencies:
- openssl=1.0.2k=1
- pip=9.0.1=py36_1
- python=3.6.1=0
- readline=6.2=2
- setuptools=27.2.0=py36_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py36_0
- xz=5.2.2=1
- zlib=1.2.8=3
- pip:
  - Markdown==2.6.6
  - pelican==3.6.3
  - jupyter>=1.0
  - ipython>=4.0
  - nbconvert>=4.0
  - beautifulsoup4
  - ghp-import==0.4.1
  - matplotlib==1.5.1

